// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cc-rules": {
            "get": {
                "description": "获取CC规则列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CC规则"
                ],
                "summary": "获取CC规则列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.CCRule"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "创建CC规则",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CC规则"
                ],
                "summary": "创建CC规则",
                "parameters": [
                    {
                        "description": "CC规则",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CCRule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/cc-rules/check/{uri}": {
            "get": {
                "description": "检查CC限制",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CC规则"
                ],
                "summary": "检查CC限制",
                "parameters": [
                    {
                        "type": "string",
                        "description": "请求URI",
                        "name": "uri",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/cc-rules/{id}": {
            "get": {
                "description": "获取CC规则",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CC规则"
                ],
                "summary": "获取CC规则",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "规则ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.CCRule"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "更新CC规则",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CC规则"
                ],
                "summary": "更新CC规则",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "规则ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "CC规则",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CCRule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除CC规则",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CC规则"
                ],
                "summary": "删除CC规则",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "规则ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/rules/versions": {
            "post": {
                "description": "创建规则版本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "规则版本"
                ],
                "summary": "创建规则版本",
                "parameters": [
                    {
                        "description": "规则版本",
                        "name": "version",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RuleVersion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/rules/{rule_id}/sync-logs": {
            "get": {
                "description": "获取同步日志",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "规则版本"
                ],
                "summary": "获取同步日志",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "规则ID",
                        "name": "rule_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.RuleSyncLog"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rules/{rule_id}/versions": {
            "get": {
                "description": "获取规则版本列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "规则版本"
                ],
                "summary": "获取规则版本列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "规则ID",
                        "name": "rule_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.RuleVersion"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rules/{rule_id}/versions/{version}": {
            "get": {
                "description": "获取规则版本",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "规则版本"
                ],
                "summary": "获取规则版本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "规则ID",
                        "name": "rule_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "版本号",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.RuleVersion"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CCRule": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "规则ID",
                    "type": "integer"
                },
                "limit_rate": {
                    "description": "限制速率",
                    "type": "integer"
                },
                "limit_unit": {
                    "description": "限制单位",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "time_window": {
                    "description": "时间窗口",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "uri": {
                    "description": "请求URI",
                    "type": "string"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "model.RuleSyncLog": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "日志ID",
                    "type": "integer"
                },
                "message": {
                    "description": "详细信息",
                    "type": "string"
                },
                "rule_id": {
                    "description": "规则ID",
                    "type": "integer"
                },
                "status": {
                    "description": "同步状态",
                    "type": "string"
                },
                "sync_type": {
                    "description": "同步类型",
                    "type": "string"
                },
                "version": {
                    "description": "版本号",
                    "type": "integer"
                }
            }
        },
        "model.RuleVersion": {
            "type": "object",
            "properties": {
                "change_type": {
                    "description": "变更类型(create/update/delete)",
                    "type": "string"
                },
                "content": {
                    "description": "规则内容",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "created_by": {
                    "description": "创建者",
                    "type": "integer"
                },
                "hash": {
                    "description": "内容哈希值",
                    "type": "string"
                },
                "id": {
                    "description": "版本ID",
                    "type": "integer"
                },
                "rule_id": {
                    "description": "规则ID",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "version": {
                    "description": "版本号",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "wArmor规则引擎API服务",
	Description:      "wArmor规则引擎API接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
