# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 10
  write_timeout: 10
  shutdown_timeout: 5

# MySQL配置
mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "waf"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
  conn_max_idle_time: 600

# 日志配置
log:
  level: "info"
  filename: "logs/waf.log"
  max_size: 100
  max_age: 30
  max_backups: 10
  compress: true

# 规则配置
rule:
  # 规则同步间隔(秒)
  sync_interval: 60
  # 规则缓存时间(秒)
  cache_ttl: 3600
  # 规则版本检查间隔(秒)
  version_check_interval: 30 