# IP黑白名单规则模板
ip_list_rules:
  - name: "IP黑名单"
    type: "ip"
    rule_variable: "request_ip"
    patterns:
      - "192\\.168\\.1\\.[0-9]+"
      - "10\\.0\\.0\\.[0-9]+"
    description: "IP黑名单规则"
    action: "block"
    status: "enabled"
    priority: 100
    severity: "high"
    rules_operation: "and"
    message: "IP已被封禁"

# 正则匹配规则模板
regex_rules:
  - name: "敏感路径检测"
    type: "regex"
    rule_variable: "request_uri"
    patterns:
      - "\\.git"
      - "\\.svn"
      - "\\.env"
      - "wp-config\\.php"
    description: "检测敏感路径访问"
    action: "block"
    status: "enabled"
    priority: 90
    severity: "medium"
    rules_operation: "or"
    message: "访问敏感路径"

# SQL注入规则模板
sql_injection_rules:
  - name: "SQL注入检测"
    type: "sqli"
    rule_variable: "request_args"
    patterns:
      - "select.*from"
      - "insert.*into"
      - "update.*set"
      - "delete.*from"
      - "drop.*table"
      - "truncate.*table"
      - "union.*select"
      - "or\\s+1=1"
      - "exec\\s+.*"
      - "--"
      - "\\/\\*.*\\*\\/"
    description: "检测SQL注入攻击"
    action: "block"
    status: "enabled"
    priority: 95
    severity: "high"
    rules_operation: "or"
    message: "检测到SQL注入攻击"

# XSS规则模板
xss_rules:
  - name: "XSS攻击检测"
    type: "xss"
    rule_variable: "request_args"
    patterns:
      - "<script"
      - "javascript:"
      - "vbscript:"
      - "onload="
      - "onerror="
      - "onclick="
      - "onmouseover="
      - "eval%s*%("
      - "document%.cookie"
      - "document%.write"
    description: "检测XSS攻击"
    action: "block"
    status: "enabled"
    priority: 95
    severity: "high"
    rules_operation: "or"
    message: "检测到XSS攻击" 